
name: 'data_pipeline_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which folder to look for models in.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  data_pipeline_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      materialized: view
    marts:
      materialized: table

profile: 'default'
